### ISSUE TITLE
Enable return-await

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/opstooling-js-style#3]
https://eslint.org/docs/rules/no-return-await says the following

> There are a few reasons you might want to turn this rule off:

> If you want to use await to denote a value that is a thenable
> If you do not want the performance benefit of avoiding return await
> If you want the functions to show up in stack traces (useful for debugging purposes)

The last point seems to be the most relevant. Related to that, there's a rule in typescript-eslint:

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md

`@typescript-eslint/return-await": ["error", "always"]` would require us to _always_ use `return await promise` whereas `["error", "never"]` would disallow us to use `return await promise` and always use `return promise` instead.

@paritytech/opstooling let's vote in the comments.

---

Useful resources:

- https://jakearchibald.com/2017/await-vs-return-vs-return-await/
- https://stackoverflow.com/questions/69436431/nodejs-should-we-return-instead-of-await-to-improve-performance

---

Inspired by https://github.com/paritytech/matrix-admin-bot/pull/2#discussion_r871120386

**Comment by joao-paulo-parity** [comment]
I'm in favor of `@typescript-eslint/return-await": ["error", "always"]` for better stack traces. The very subtle performance improvement of `return promise` won't matter in most cases.

**Comment by mutantcornholio** [comment]
I personally like `@typescript-eslint/return-await": ["error", "never"]` for more concise code, but I can totally live with `["error", "always"]`.

**Comment by joao-paulo-parity** [comment]
@mordamax ?

**Comment by mordamax** [comment]
I'm fine with both, thx
